# Generated by Django 4.0.4 on 2022-06-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_order', models.PositiveIntegerField()),
                ('product_cost', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('product_details', models.CharField(max_length=255)),
                ('product_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=255),
        ),
    ]
