# Generated by Django 4.0.4 on 2022-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_products_pick_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_available',
            new_name='order_available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_cost',
        ),
        migrations.AddField(
            model_name='products',
            name='order_cost',
            field=models.CharField(blank=True, default='0.00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pick_cost',
            field=models.CharField(blank=True, default='0.00', max_length=255, null=True),
        ),
    ]
